#!/bin/bash

set -xeo pipefail

echo $BUILDKITE_PLUGIN_GIT_PUSH_MACHINE
echo $BUILDKITE_PLUGIN_HEROKU_MACHINE

# Reads either a value or a list from plugin config
function plugin_read_list() {
  local prefix="BUILDKITE_PLUGIN_GIT_PUSH_$1"
  local parameter="${prefix}_0"

  if [[ -n "${!parameter:-}" ]]; then
    local i=0
    local parameter="${prefix}_${i}"
    while [[ -n "${!parameter:-}" ]]; do
      echo "${!parameter}"
      i=$((i+1))
      parameter="${prefix}_${i}"
    done
  elif [[ -n "${!prefix:-}" ]]; then
    echo "${!prefix}"
  fi
}

while read -r line ; do
  echo "$line"
done <<< "$(plugin_read_list MACHINE)"

echo "machine $BUILDKITE_PLUGIN_GIT_PUSH_MACHINE\n\tlogin $BUILDKITE_PLUGIN_GIT_PUSH_LOGIN\n\tpassword $BUILDKITE_PLUGIN_GIT_PUSH_PASSWORD" > ~/.netrc

if git remote | grep -w $name ; then
  git remote set-url underworld $BUILDKITE_PLUGIN_GIT_PUSH_REMOTE
else
  git remote add underworld $BUILDKITE_PLUGIN_GIT_PUSH_REMOTE
if

git fetch origin && git push underworld $BUILDKITE_BRANCH:master --force

git remote rm underworld

exit 0
